# NumPy: Numerical Python package 

- [NumPy](https://www.numpy.org) is perhaps the most important  package for numerical computing in Python
- The n-dimentional array in NumPy is used as a a basic object in most Python packages for data exchange
  - We will look at its methods and semantics through examples
- Some of the most important features of NumPy are 
  - `ndarray`: multidimensional array for **fast and efficient array-oriented operations** and arithmetics
  - Mathematical functions for **fast operation on arrays without using loops and iterations**
  - Tools for I/O to and from disk
  - Linear algebra
  - Random generation 
  - API (application programming interface) to connect NumPy with C and C++ libraries

## 1. NumPy `ndarray`: a multidimensional array object
`ndarray` is an array that can have an arbirary number of dimensions. We will see examples in 2D and 3D for calculations.

**Its main feature: vector calculations are extremely fast!**

Let's see how much faster an `ndarray` object is compared to a loop (with comprehension).
- The magic command `%time` measures the duration of a single command.
- The magic command `%timeit` measures the duration of a single command, running it multiple times in order to provide an error.
- The magic command `%%time` (which we will use in other notebooks) measures the duration of a block of  commands.

In [ ]:
import numpy as np
import math as m

nmax = 100000

# For calculations with a comprehension on a list
my_list = list(range(1,nmax))

# For direct calculations on a numpy array
my_arr = np.arange(1,nmax)

n_test = 100

%time for _ in range(n_test): my_list2 = [x*2 for x in my_list]

%time for _ in range(n_test): my_arr2 = my_arr * 2

print(type(my_list), type(my_list2))
print(type(my_arr), type(my_arr2))

- `user`: The cumulative time spent by all the CPUs during the computation
- `sys`: The cumulative time spent by all the CPUs during system-related tasks such as memory allocation.
- `Wall time`: The actual time spent in running the process from start to finish, as if it was measured by a human looking at a clock on a wall.

__NumPy based algorithms are generally 10 to 100 times faster than pure Python counterparts!__

Here is another measurement of speedup: it comes with an error bar on the wall-clock time, by running the same command more than once.

In [ ]:
%timeit for _ in range(n_test): my_list2 = [x*2 for x in my_list]

%timeit for _ in range(n_test): my_arr2 = my_arr * 2

In the examples below you should also notice how much `**` costs in terms of runtime.  **Never forget to try to optimize small things like these: they can make a big difference.**

In [ ]:
%timeit for _ in range(n_test): my_list3 = [x**3 for x in my_list]
%timeit for _ in range(n_test): my_list3 = [x*x*x for x in my_list]

%timeit for _ in range(n_test): my_arr3 = my_arr **3
%timeit for _ in range(n_test): my_arr3 = my_arr * my_arr * my_arr

In [ ]:
%timeit for _ in range(n_test): my_list3 = [m.log(x**2) for x in my_list]
%timeit for _ in range(n_test): my_list3 = [m.log(x*x) for x in my_list]

%timeit for _ in range(n_test): my_arr3 = np.log(my_arr**2)
%timeit for _ in range(n_test): my_arr3 = np.log(my_arr*my_arr)

## 2. Creating `ndarray`s

`arange()` is an upgrade to `range()` we already met. It generates the numbers from the first to the second argument, separated by the step given as the third argument.

In [ ]:
my_arr = np.arange(1,100,0.5)
print(type(my_arr))
print(my_arr)

### Array of uniformly sampled random numbers (between 0 and 1)

In [ ]:
np.random.rand()

In [ ]:
print(type(np.random.rand()))

To create `ndarray`s, the user needs to **specify the dimensions and the size of the array to be created**.

In [ ]:
np.random.rand(10,3)

In [ ]:
print(type(np.random.rand(10,3)))

In [ ]:
np.random.rand(2,3,4)

### Creating an `ndrray` of uniformly sampled random numbers

If you need a different interval, use `np.random.uniform(start, stop, shape_tuple)`.

In [ ]:
np.random.uniform(2,5)

In [ ]:
np.random.uniform(2,5,(10,3))

In [ ]:
np.random.uniform(2,5,(2,3,4))

### Creating an `ndarray` of zeros, ones, a repeated number
- `np.zeros(shape_tuple)`
- `np.ones(shape_tuple)`
- `np.full(shape_tuple, fill_value=...)`

In [ ]:
np.zeros((3,4,5,6))

In [ ]:
np.ones((3,4))

In [ ]:
np.full((2,6), fill_value=3.12)

### You can multiply an `ndarray` by a constant on both sides

In [ ]:
B = np.ones((3,4))
val = 3.6*B
print(val)

print(val*2.3)

But `np.full` is faster than multuplying ones by a scalar.

In [ ]:
N = 1000000

%timeit 3.6*np.ones(N)

%timeit np.full(N, fill_value=3.6)

### Identity array

In [ ]:
data = np.identity(7)
print(data)

### Custom array
You can use lists and tuples

In [ ]:
np.array([[1,2],[1,2],[1,2],[1,2]])

In [ ]:
np.array([(1,2),(1,2),(1,2),(1,2)])

In [ ]:
np.array(([1,2],[1,2],[1,2],[1,2]))

In [ ]:
np.array(((1,2),(1,2),(1,2),(1,2)))

In [ ]:
np.array(([1,2],(1,2),(1,2),[1,2]))

But watch out for the effect of using sets

In [ ]:
np.array({(1,2),(3,4),(1,2),(1,2)})

## 3. Operations with arrays

In [ ]:
C = np.full((4,4), fill_value=-4.3)
print(C)

D = np.identity(4)
print(D)

In [ ]:
print(C + D)

In [ ]:
print(D - C)

As we saw above, multiplication by a number (on either side of the `ndarray`) happens **element-wise**.

Let's check division.

In [ ]:
print(C/2.3)

Notice that below 0.5 is promoted to an array that has the shape of the denominator (`D`) and 0.5 in all its entries; the division then happens entry by entry

In [ ]:
D = np.array(((1,2),(1,2),(1,2),(1,2)))
print(D)
print(0.5/D)

### Looking for matrix multiplication?  `numpy.matmul` is your answer.

In [ ]:
E = np.array([[2,3,4], [2,1,0]])
F = np.array([[1,1], [1,3], [5,2]])

print(E)
print(F)

print(np.matmul(E,F))
print(np.matmul(F,E))

### Applying functions to `ndarray`s

This requires using functions that accept NumPy `ndarray`s as arguments.  E.g., `np.sin` and not `math.sin`

In [ ]:
data = np.arange(1,10)

datasq = data**2 # This is the power operator for NumPy `ndarray`s

data_2 = np.log(datasq) + np.sin(data*np.pi)

In [ ]:
print(data)
print(datasq)
print(data_2)

The following fails because the `math` module does not know what to do with the `ndarray` passed as argument of `sqrt`.

In [ ]:
m.sqrt(datasq)

There is a possible workaround (see next line), but with `ndarray`s you should always use NumPy functions for the runtime benefits they give you on larger collections of numbers.

In [ ]:
tmp = [m.sqrt(val) for val in datasq]
print(tmp)

In [ ]:
tmp = np.arange(1,10000)

%timeit [m.sqrt(val) for val in tmp]
%timeit np.sqrt(tmp)

## 4. Vectorizing functions

To tackle the bottleneck of `for` loops, NumPy provides a vectorization functionality that maps a function over a sequence efficiently.

Let's define a simple example function `pyfunc`.

In [ ]:
def pyfunc(a, b, c, d):
    if c*a >= b:
        return a + b + d
    else:
        return a - b - d

# Checking it works
a = 1
b = 2
c = 3
d = 4

pyfunc(a, b, c, d)

The interpreter does not know how to handle `pyfunc` when it its first argument is a NumPy array.

In [ ]:
a = np.arange(5)
pyfunc(a, b, c, d)

To enable this, we need to create a **vectorized version** of `pyfunc`.
This weaves throught the input creating tuples of length 4 and running `pyfunc` on it.

In [ ]:
vpyfunc = np.vectorize(pyfunc)

# Check it works
print(vpyfunc(a, b, c, d))
print(vpyfunc(a, a, c, d))
print(vpyfunc(a, a, a, d))
print(vpyfunc(a, a, a, a))

In [ ]:
# Notice that the arguments can also be other kinds of collections,
# which is not the case for the original function
print(vpyfunc(list(a), tuple(a), c, d))
print(pyfunc(list(a), tuple(a), c, d))

In [ ]:
# Also notice that the unique weaving through the collections has to be possible, which is not the case below. 
print(vpyfunc((1,2), (1,2,3), c, d))

We can enforce the output type.

In [ ]:
res = vpyfunc(a, b, c, d)
print(type(res[0]))

vpyfunc =  np.vectorize(pyfunc, otypes=[float])
res = vpyfunc(a, b, c, d)
print(type(res[0]))

We can also skip vectorizing on specific arguments, e.g., the 2nd and 4th ones (arguments 1 and 3).

In [ ]:
vpyfunc = np.vectorize(pyfunc, otypes=[float], excluded=[1,3])

print(vpyfunc(a, b, a, d))
print(vpyfunc(b, b, c, d))

Indeed it fails if the second or the fourth argument is not a single value.

In [ ]:
print(vpyfunc(a, a, c, d))

In [ ]:
print(vpyfunc(a, b, c, a))

Finally, notice that
1. calls to NumPy functions are faster than calls to `math` embedded in a vectorized function
1. vectorization wins over comprehensions when the complexity of the operation you are repeating is high

In [ ]:
def pyfunc(x):
    return m.log(x*x) - m.sin(x)*m.cos(x)

vpyfunc = np.vectorize(pyfunc)

%timeit np.log(tmp)*np.log(tmp) - np.sin(tmp)*np.cos(tmp)
%timeit vpyfunc(tmp)

In [ ]:
%timeit [m.log(x)*m.log(x) - m.sin(x)*m.cos(x) for x in tmp]
%timeit vpyfunc(tmp)

def pyfunc(x):
    return m.log(x)

vpyfunc = np.vectorize(pyfunc)

# Low complexity: comprehension is faster
%timeit [m.log(x) for x in tmp]
%timeit vpyfunc(tmp)

## 5. Shape of arrays
Every `ndarray` is characterized by its 
- shape
- size
- number of dimensions
- type of data

In [ ]:
data = np.array([[-1., 2.3], [2.3, 4.5], [-8.4, 1.9]])
print(data)
print("shape: ", data.shape)
print("size: ", data.size)
print("dimensions: ", data.ndim)
print("data type: ", data.dtype)

### Change type of data

In [ ]:
data_int = np.array(data, dtype=np.int64)
print(f"original data:\n {data}\n")
print(f"new data:\n {data_int}\n")
print("new data type: ", data_int.dtype)

### Reshaping arrays

In [ ]:
data = np.arange(1,37)
print(data)
print(data.ndim)
print(data.shape)

In [ ]:
mat1 = data.reshape(3,12)
print(mat1)
print(mat1.ndim)
print(mat1.shape)

In [ ]:
mat2 = mat1.reshape(6,6)
print(mat2)

In [ ]:
mat3 = mat1.reshape(4,3,3)
print(mat3)

NumPy has its checks on reshaping, so that you do not lose information or add random numbers.

In the following example $10\times 2\times 2\neq 36$, so you hit an error.

In [ ]:
mat4 = mat1.reshape(10,2,2)
print(mat4)

__Note that the original data array has not been modified__

In [ ]:
data

If we want to modify the original array, we need to run `data = data.reshape(6,6)`

### Creating an array with the same shape of an existing array

`ones_like` will give you array elements equal to 1, shaped like its argument

In [ ]:
print(mat2)

In [ ]:
data2 = np.ones_like(mat2)
print(data2)

`zeros_like` will give you array elements equal to 0, shaped like its argument

In [ ]:
np.zeros_like(mat2)

`full_like` will preserve the shape of the first argument, and give you elements identical to the second argument.

In [ ]:
np.full_like(mat2, -4.5, dtype=float)

Notice the importance of `dtype`!  The default is `int64` because it is the data type in `mat2`.

In [ ]:
np.full_like(mat2, -4.5)

Naturally, you can also use the NumPy types.

In [ ]:
np.full_like(mat2, fill_value=-4.5, dtype=np.float64)

In [ ]:
np.full_like(mat2, 'F', dtype=str) # Will fail without the dtype!

`empty_like` will give you uninitialized (arbitrary) array elements (not necessarily 0's)

In [ ]:
y = np.empty_like(mat2)
print(y)

## 6. Indexing and slicing

The indexing starts with 0, as usual.

In [ ]:
data = np.arange(20).reshape(4,5)
data_l = [[ 0,  1,  2,  3,  4],
          [ 5,  6,  7,  8,  9],
          [10, 11, 12, 13, 14],
          [15, 16, 17, 18, 19]]
print(data)
print(data_l)

In [ ]:
print(data[2:4,2:4])

Note that getting the same with a list requires a more elaborate (and less intuitive) syntax

In [ ]:
print(data_l[2:4])

In [ ]:
print([el[2:4] for el in data_l[2:4]])

### Extracting columns

In [ ]:
print(data)

In [ ]:
data[:,3] # Fetch the element with index 3 for all values of the 1st index

In [ ]:
data[1:,:] # Fetch all entries for values of the 1st index from 1 onwards

Slicing for a specific index that is out of bounds will cause an error.

However slicing out of bound indices using `:` will not: NumPy will return as many entries as it can.

In [ ]:
data[20]

In [ ]:
data[20:]

In [ ]:
data[20:20]

In [ ]:
data[:2,3:]

In [ ]:
data[:2,3:70]

**As with the lists, all operations return a reference to the original array, unless you make a copy**.

In the example below, `y` is a newly defined numpy array, but `x` is not

In [ ]:
x = data[:2,1:3]
y = np.array(data[:2,1:3])
print(x)
print(y)

In [ ]:
x[0][1] = -5.55
y[0][1] = 500
print(x)
print(y)
print(data)

We have modified not just `x`, but also the original data array!  The same is not true for `y`.

The key difference is that in the `y` case we created a new copy of `data` by calling the constructor `numpy.array`.

## 7. Converting and casting
The following array entries are of integer type.

In [ ]:
data = np.arange(9).reshape(3,3)
data.dtype

Sometimes you might want to change its type for floating point calculations

In [ ]:
data[1,0] = -np.pi
data

In [ ]:
data_float = data.astype(np.float64)
print(data_float)

In [ ]:
data_float[1,0] = -np.pi
print(data_float)

Note that `astype()` returned a copy of the array and our original array `data` has not been modified

In [ ]:
print(data)

## 8. Boolean arrays
As with all operations, also logical operations are vectorised.

In [ ]:
data = np.random.normal(0, 1., 9).reshape(3,3) # Same as np.random.normal(0, 1., (3,3))
print(data)

res = data > 0
print(res)

**Logical arrays can be used to slice and index an array!**

In this case we want the array with just the positive cells.

In [ ]:
posdata = data[res]
print(posdata)
print("# positives: ", len(posdata))

Since booleans are converted automatically to 0 and 1, you can easily count them by using the `sum` function

In [ ]:
print("Sum of boolean: ", res.sum())

Note that the original shape is lost

In [ ]:
print(type(posdata))
print("Shape: ", np.shape(posdata))

**This implies that slicing with a boolean array creates a new array and not a reference to the original array.**

`all()` and `any()` are important methods when dealing with Boolean arrays.
- `all()` checks if all entries are `True`
- `any()` checks that at least on entry is `True`

In [ ]:
print(data>0)

print((data>0).all())

print((data>0).any())

## 9. I/O of NumPy objects

NumPy provides built-in functions to easily store and read `ndarray`s in binary and text format **without iterating** over each element.
- Use `save()` and `load()` with binary files (`.npy`).
- Use `savetxt()` and `loadtxt()` with textfiles.

### I/O with `ndarray`s: binary and text files

See [Input/Output with numpy](https://numpy.org/doc/stable/reference/routines.io.html) for a general reference.


**Save to file with `save()` and `savetxt()`**

In [2]:
import numpy as np

In [3]:
matrix = np.random.randn(10,5)
print(matrix)

fname = 'npdata1'
np.save(fname+'.npy', matrix)
np.savetxt(fname+'.txt', matrix)

[[ 1.35065349 -0.89351483  1.51465126 -0.81825667 -0.6769455 ]
 [-0.69937985 -2.58782013 -0.73445822  0.60384648  0.91959184]
 [-0.63976413  0.19800412 -0.49840486  0.3180665  -0.08596517]
 [ 0.62028979  0.71720961 -1.28246964 -1.16915992  1.05509721]
 [ 1.41467567  0.25935946  0.4461015   0.047537    1.04548414]
 [ 0.6049415   0.40807223  0.70308513  0.25359969 -0.30669943]
 [-1.3251744   0.65858306 -0.02299989  1.41438823 -1.31782849]
 [ 0.10259501  1.50426579 -0.1294457   0.44803667  1.16760315]
 [ 0.72638053  1.59061068 -1.07224389 -1.84917611 -2.89253048]
 [ 0.78634829 -1.93203474  0.05871224  0.84135429 -0.06282569]]


Naturally, the binary file uses less memory.

In [4]:
!ls -lrth npdata1*

-rw-r--r--  1 francesco  staff   528B Nov 28 12:20 npdata1.npy
-rw-r--r--  1 francesco  staff   1.2K Nov 28 12:20 npdata1.txt


**Reading is also simple with `load()` and `loadtxt()`**

In [5]:
vals = np.load(fname+'.npy')

assert (vals==matrix).all()

In particular [numpy.loadtxt](https://numpy.org/doc/stable/reference/generated/numpy.loadtxt.html#numpy.loadtxt) is very handy for quick reading of data from text files.

In [6]:
data = np.loadtxt(fname+'.txt')

assert (data==matrix).all()

Slice it to extract columns.

In [7]:
x = data[:,0]
y = data[:,1]
z = data[:,2]
t = data[:,3]
E = data[:,4]

print(z)

[ 1.51465126 -0.73445822 -0.49840486 -1.28246964  0.4461015   0.70308513
 -0.02299989 -0.1294457  -1.07224389  0.05871224]


We can also think of this txt file as having data stored per event (line) in columns (variables).  E.g., the following structure
```
#x   #y   #z   #t   #energy
...  ...  ...  ...  ...
...  ...  ...  ...  ...
...  ...  ...  ...  ...
```

Since this is a typical usecase, with NumPy we can also **read the data directly into arrays per column** without reading in all data and then manipulating it.  `loadtxt` has the following options to do this:
- `usecols=(a,b,c)` or `usecols=d` reads only the column(s) specified
- `unpack=True` transposes data to go in columns

In [8]:
x,z = np.loadtxt(fname+'.txt', unpack=True, usecols=(0,2))

assert (z==data[:,2]).all()

Similarly, [nump.savetxt](https://numpy.org/doc/stable/reference/generated/numpy.savetxt.html) is very convenient to **write `ndarrays` by column to textfile** in a formatted fashion.

In [9]:
fname = 'npdata2.txt'

np.savetxt(fname, (x, y, z, t, E), delimiter="\t", fmt="%.3f")

Note that the "columns" get written to lines

In [10]:
!cat npdata2.txt

1.351	-0.699	-0.640	0.620	1.415	0.605	-1.325	0.103	0.726	0.786
-0.894	-2.588	0.198	0.717	0.259	0.408	0.659	1.504	1.591	-1.932
1.515	-0.734	-0.498	-1.282	0.446	0.703	-0.023	-0.129	-1.072	0.059
-0.818	0.604	0.318	-1.169	0.048	0.254	1.414	0.448	-1.849	0.841
-0.677	0.920	-0.086	1.055	1.045	-0.307	-1.318	1.168	-2.893	-0.063


In [11]:
!cat npdata1.txt

1.350653491431635711e+00 -8.935148278607615291e-01 1.514651260233513819e+00 -8.182566698926065918e-01 -6.769454953212058479e-01
-6.993798493725659204e-01 -2.587820126455060876e+00 -7.344582209951155960e-01 6.038464847947373482e-01 9.195918401979279455e-01
-6.397641300423836386e-01 1.980041191290242697e-01 -4.984048554436494860e-01 3.180664976573894243e-01 -8.596517271220992240e-02
6.202897862799350293e-01 7.172096066083463173e-01 -1.282469639429090424e+00 -1.169159923356819064e+00 1.055097212407873908e+00
1.414675667516563484e+00 2.593594642125067740e-01 4.461015029739706095e-01 4.753700372583134770e-02 1.045484135260912772e+00
6.049415015456773848e-01 4.080722275997744064e-01 7.030851273769087584e-01 2.535996872547639502e-01 -3.066994273870505272e-01
-1.325174402408220375e+00 6.585830565860206764e-01 -2.299988720364786951e-02 1.414388225078185402e+00 -1.317828488862913261e+00
1.025950121194738746e-01 1.504265785744997919e+00 -1.294457045420903951e-01 4.480366741000231245e-01 1.1676031

Cleanup

In [12]:
!rm npdata*

The [Python Data Analysis Library (pandas)](http://pandas.pydata.org) provides even more efficient tools and data formats to handle data for analysis and their storage to file.