# NumPy: Numerical Python package 

- [NumPy](https://www.numpy.org) is perhaps the most important  package for numerical computing in Python
- The n-dimentional array in NumPy is used as a a basic object in most Python packages for data exchange
  - We will look at its methods and semantics through examples
- Some of the most important features of NumPy are 
  - `ndarray`: multidimensional array for **fast and efficient array-oriented operations** and arithmetics
  - Mathematical functions for **fast operation on arrays without using loops and iterations**
  - Tools for I/O to and from disk
  - Linear algebra
  - Random generation 
  - API (application programming interface) to connect NumPy with C and C++ libraries

# 1. NumPy `ndarray`: a multidimensional array object
`ndarray` is an array that can have an arbirary number of dimensions. We will see examples in 2D and 3D for calculations.

**Its main feature: vector calculations are extremely fast!**

Let's see how much faster an `ndarray` object is compared to a loop (with comprehension).
- The magic command `%time` measures the duration of a single command.
- The magic command `%timeit` measures the duration of a single command, running it multiple times in order to provide an error.
- The magic command `%%time` (which we will use in other notebooks) measures the duration of a block of  commands.

In [ ]:
import numpy as np
import math as m

nmax = 100000

# For calculations with a comprehension on a list
my_list = list(range(1,nmax))

# For direct calculations on a numpy array
my_arr = np.arange(1,nmax)

n_test = 100

%time for _ in range(n_test): my_list2 = [x*2 for x in my_list]

%time for _ in range(n_test): my_arr2 = my_arr * 2

print(type(my_list), type(my_list2))
print(type(my_arr), type(my_arr2))

- `user`: The cumulative time spent by all the CPUs during the computation
- `sys`: The cumulative time spent by all the CPUs during system-related tasks such as memory allocation.
- `Wall time`: The actual time spent in running the process from start to finish, as if it was measured by a human looking at a clock on a wall.

__NumPy based algorithms are generally 10 to 100 times faster than pure Python counterparts!__

Here is another measurement of speedup: it comes with an error bar on the wall-clock time, by running the same command more than once.

In [ ]:
%timeit for _ in range(n_test): my_list2 = [x*2 for x in my_list]

%timeit for _ in range(n_test): my_arr2 = my_arr * 2

The slowest run took 5.04 times longer than the fastest. This could mean that an intermediate result is being cached.
1.52 s ± 914 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
47.9 ms ± 13.3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In the examples below you should also notice how much `**` costs in terms of runtime.  **Never forget to try to optimize small things like these: they can make a big difference.**

In [ ]:
%timeit for _ in range(n_test): my_list3 = [x**3 for x in my_list]
%timeit for _ in range(n_test): my_list3 = [x*x*x for x in my_list]

%timeit for _ in range(n_test): my_arr3 = my_arr **3
%timeit for _ in range(n_test): my_arr3 = my_arr * my_arr * my_arr

2.67 s ± 576 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
1.94 s ± 638 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
68.7 ms ± 7.89 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
60.2 ms ± 7.04 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
%timeit for _ in range(n_test): my_list3 = [m.log(x**2) for x in my_list]
%timeit for _ in range(n_test): my_list3 = [m.log(x*x) for x in my_list]

%timeit for _ in range(n_test): my_arr3 = np.log(my_arr**2)
%timeit for _ in range(n_test): my_arr3 = np.log(my_arr*my_arr)

3.64 s ± 376 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
3.05 s ± 735 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
268 ms ± 67.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
286 ms ± 58.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


# 2. Creating `ndarray`s

`arange()` is an upgrade to `range()` we already met. It generates the numbers from the first to the second argument, separated by the step given as the third argument.

In [ ]:
my_arr = np.arange(1,100,0.5)
print(type(my_arr))
print(my_arr)

<class 'numpy.ndarray'>
[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5
 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5 20.  20.5 21.  21.5
 22.  22.5 23.  23.5 24.  24.5 25.  25.5 26.  26.5 27.  27.5 28.  28.5
 29.  29.5 30.  30.5 31.  31.5 32.  32.5 33.  33.5 34.  34.5 35.  35.5
 36.  36.5 37.  37.5 38.  38.5 39.  39.5 40.  40.5 41.  41.5 42.  42.5
 43.  43.5 44.  44.5 45.  45.5 46.  46.5 47.  47.5 48.  48.5 49.  49.5
 50.  50.5 51.  51.5 52.  52.5 53.  53.5 54.  54.5 55.  55.5 56.  56.5
 57.  57.5 58.  58.5 59.  59.5 60.  60.5 61.  61.5 62.  62.5 63.  63.5
 64.  64.5 65.  65.5 66.  66.5 67.  67.5 68.  68.5 69.  69.5 70.  70.5
 71.  71.5 72.  72.5 73.  73.5 74.  74.5 75.  75.5 76.  76.5 77.  77.5
 78.  78.5 79.  79.5 80.  80.5 81.  81.5 82.  82.5 83.  83.5 84.  84.5
 85.  85.5 86.  86.5 87.  87.5 88.  88.5 89.  89.5 90.  90.5 91.  91.5
 92.  92.5 93.  93.5 94.  94.5 95.  95.5 96.  96.5 97

### Array of uniformly sampled random numbers (between 0 and 1)

In [ ]:
np.random.rand()

0.11541830739892989

In [ ]:
print(type(np.random.rand()))

<class 'float'>


To create `ndarray`s, the user needs to **specify the dimensions and the size of the array to be created**.

In [ ]:
np.random.rand(10, #dimension
                3) #size of array
                #10 rows and 3 columns

array([[0.88953935, 0.63665937, 0.10926234],
       [0.04895562, 0.41820439, 0.33942003],
       [0.28454493, 0.58908694, 0.42493875],
       [0.07842488, 0.00363867, 0.34192381],
       [0.28376782, 0.59135571, 0.6983484 ],
       [0.22540364, 0.38769161, 0.6721831 ],
       [0.48134517, 0.43530523, 0.42674899],
       [0.10870853, 0.99923687, 0.04281173],
       [0.20404063, 0.5604009 , 0.40573829],
       [0.60171458, 0.32750921, 0.8374764 ]])

In [ ]:
print(type(np.random.rand(10,3)))

<class 'numpy.ndarray'>


In [ ]:
np.random.rand(2,3,4)

array([[[0.4127094 , 0.28586946, 0.22435393, 0.30164941],
        [0.85093957, 0.76351524, 0.1730462 , 0.54009423],
        [0.6206978 , 0.28409171, 0.04123215, 0.15683935]],

       [[0.67060337, 0.59914944, 0.74362101, 0.48771859],
        [0.24217929, 0.8611501 , 0.64455147, 0.01297422],
        [0.32217993, 0.66329022, 0.77715213, 0.49956312]]])

### Creating an `ndrray` of uniformly sampled random numbers

If you need a different interval, use `np.random.uniform(start, stop, shape_tuple)`.

In [ ]:
np.random.uniform(2,5)

3.4034808551395965

In [ ]:
np.random.uniform(2,5,(10,3))

array([[2.58610887, 4.83840155, 3.1984866 ],
       [4.09353567, 3.89935002, 3.66582416],
       [2.19080263, 4.68818014, 3.22291796],
       [4.76111652, 4.20941011, 4.81479713],
       [2.68844836, 3.43999597, 4.26039977],
       [4.86850786, 4.25540012, 3.96406787],
       [2.04087401, 4.59167029, 3.163991  ],
       [4.8488365 , 4.3857562 , 4.03795866],
       [2.90219959, 4.41373045, 3.91169158],
       [4.31484062, 4.20248788, 4.95962276]])

In [ ]:
np.random.uniform(2,5,(2,3,4))

array([[[3.80470796, 2.15888402, 2.28724524, 4.30895436],
        [3.36826772, 2.06928587, 2.70779892, 2.50110609],
        [3.29901491, 2.51284601, 2.49487124, 2.7850042 ]],

       [[2.07551037, 4.14278787, 3.80926153, 3.63688066],
        [3.83950341, 3.85103894, 3.69043626, 2.8724956 ],
        [2.78340887, 3.66136565, 4.18498868, 4.29037212]]])

### Creating an `ndarray` of zeros, ones, a repeated number
- `np.zeros(shape_tuple)`
- `np.ones(shape_tuple)`
- `np.full(shape_tuple, fill_value=...)`

In [ ]:
np.zeros((3,4,5,6))

array([[[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
        

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.full((2,6), fill_value=3.12)

array([[3.12, 3.12, 3.12, 3.12, 3.12, 3.12],
       [3.12, 3.12, 3.12, 3.12, 3.12, 3.12]])

### You can multiply an `ndarray` by a constant on both sides

In [ ]:
B = np.ones((3,4))
val = 3.6*B
print(val)

print(val*2.3)

[[3.6 3.6 3.6 3.6]
 [3.6 3.6 3.6 3.6]
 [3.6 3.6 3.6 3.6]]
[[8.28 8.28 8.28 8.28]
 [8.28 8.28 8.28 8.28]
 [8.28 8.28 8.28 8.28]]


But `np.full` is faster than multuplying ones by a scalar.

In [ ]:
N = 1000000

%timeit 3.6*np.ones(N)

%timeit np.full(N, fill_value=3.6)

10.3 ms ± 2.57 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
3.88 ms ± 1.85 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


### Identity array

In [ ]:
data = np.identity(7)
print(data)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


### Custom array
You can use lists and tuples

In [ ]:
np.array([[1,2],[1,2],[1,2],[1,2]])

array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2]])

In [ ]:
np.array([(1,2),(1,2),(1,2),(1,2)])

array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2]])

In [ ]:
np.array(([1,2],[1,2],[1,2],[1,2]))

array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2]])

In [ ]:
np.array(((1,2),(1,2),(1,2),(1,2)))

array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2]])

In [ ]:
np.array(([1,2],(1,2),(1,2),[1,2]))

array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2]])

# But watch out for the effect of using sets

In [ ]:
np.array({(1,2),(3,4),(1,2),(1,2)})

array({(1, 2), (3, 4)}, dtype=object)

# 3. Operations with arrays

In [ ]:
C = np.full((4,4), fill_value=-4.3)
print(C)

D = np.identity(4)
print(D)

[[-4.3 -4.3 -4.3 -4.3]
 [-4.3 -4.3 -4.3 -4.3]
 [-4.3 -4.3 -4.3 -4.3]
 [-4.3 -4.3 -4.3 -4.3]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
print(C + D)

[[-3.3 -4.3 -4.3 -4.3]
 [-4.3 -3.3 -4.3 -4.3]
 [-4.3 -4.3 -3.3 -4.3]
 [-4.3 -4.3 -4.3 -3.3]]


In [ ]:
print(D - C)

[[5.3 4.3 4.3 4.3]
 [4.3 5.3 4.3 4.3]
 [4.3 4.3 5.3 4.3]
 [4.3 4.3 4.3 5.3]]


As we saw above, multiplication by a number (on either side of the `ndarray`) happens **element-wise**.

Let's check division.

In [ ]:
print(C/2.3)

[[-1.86956522 -1.86956522 -1.86956522 -1.86956522]
 [-1.86956522 -1.86956522 -1.86956522 -1.86956522]
 [-1.86956522 -1.86956522 -1.86956522 -1.86956522]
 [-1.86956522 -1.86956522 -1.86956522 -1.86956522]]


Notice that below 0.5 is promoted to an array that has the shape of the denominator (`D`) and 0.5 in all its entries; the division then happens entry by entry

In [ ]:
D = np.array(((1,2),(1,2),(1,2),(1,2)))
print(D)
print(0.5/D)

[[1 2]
 [1 2]
 [1 2]
 [1 2]]
[[0.5  0.25]
 [0.5  0.25]
 [0.5  0.25]
 [0.5  0.25]]


# Looking for matrix multiplication?  `numpy.matmul` is your answer.

In [ ]:
E = np.array([[2,3,4], [2,1,0]])
F = np.array([[1,1], [1,3], [5,2]])

print(E)
print(F)

print(np.matmul(E,F))
print(np.matmul(F,E))

[[2 3 4]
 [2 1 0]]
[[1 1]
 [1 3]
 [5 2]]
[[25 19]
 [ 3  5]]
[[ 4  4  4]
 [ 8  6  4]
 [14 17 20]]


### Applying functions to `ndarray`s

This requires using functions that accept NumPy `ndarray`s as arguments.  E.g., `np.sin` and not `math.sin`

In [ ]:
data = np.arange(1,10)

datasq = data**2 # This is the power operator for NumPy `ndarray`s

data_2 = np.log(datasq) + np.sin(data*np.pi)

In [ ]:
print(data)
print(datasq)
print(data_2)

[1 2 3 4 5 6 7 8 9]
[ 1  4  9 16 25 36 49 64 81]
[1.22464680e-16 1.38629436e+00 2.19722458e+00 2.77258872e+00
 3.21887582e+00 3.58351894e+00 3.89182030e+00 4.15888308e+00
 4.39444915e+00]


The following fails because the `math` module does not know what to do with the `ndarray` passed as argument of `sqrt`.

In [ ]:
m.sqrt(datasq)

TypeError: only length-1 arrays can be converted to Python scalars

There is a possible workaround (see next line), but with `ndarray`s you should always use NumPy functions for the runtime benefits they give you on larger collections of numbers.

In [19]:
import math as m

In [20]:
tmp = [m.sqrt(val) for val in datasq]
print(tmp)

NameError: name 'datasq' is not defined

In [21]:
tmp = np.arange(1,10000)

%timeit [m.sqrt(val) for val in tmp]
%timeit np.sqrt(tmp)

5.15 ms ± 1.47 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
43.6 µs ± 9.28 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


# 4. Vectorizing functions

To tackle the bottleneck of `for` loops, NumPy provides a vectorization functionality that maps a function over a sequence efficiently.

Let's define a simple example function `pyfunc`.

In [3]:
import numpy as np

In [4]:
def pyfunc(a, b, c, d):
    if c*a >= b:
        return a + b + d
    else:
        return a - b - d

# Checking it works
a = 1
b = 2
c = 3
d = 4

pyfunc(a, b, c, d)

7

The interpreter does not know how to handle `pyfunc` when it its first argument is a NumPy array.

In [5]:
a = np.arange(5)
pyfunc(a, b, c, d)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

# To enable this, we need to create a **vectorized version** of `pyfunc`. vecto_function=np.vectorize(funct)
This weaves throught the input creating tuples of length 4 and running `pyfunc` on it.

In [7]:
vpyfunc = np.vectorize(pyfunc)

# Check it works
print(vpyfunc(a, b, c, d))
print(vpyfunc(a, a, c, d))
print(vpyfunc(a, a, a, d))
print(vpyfunc(a, a, a, a))

[-6  7  8  9 10]
[ 4  6  8 10 12]
[ 4  6  8 10 12]
[ 0  3  6  9 12]


In [ ]:
# Notice that the arguments can also be other kinds of collections,
# which is not the case for the original function
print(vpyfunc(list(a), tuple(a), list(a), tuple(a)))
print(pyfunc(list(a), tuple(a), c, d))

[ 0  3  6  9 12]


TypeError: '>=' not supported between instances of 'list' and 'tuple'

In [ ]:
# Also notice that the unique weaving through the collections has to be possible, which is not the case below. 
print(vpyfunc((1,2), (1,2,3), c, d))

ValueError: operands could not be broadcast together with shapes (2,) (3,) () () 

We can enforce the output type.

In [22]:
res = vpyfunc(a, b, c, d)
print(type(res[0]))

vpyfunc =  np.vectorize(pyfunc, otypes=[float])
res = vpyfunc(a, b, c, d)
print(type(res[0]))

TypeError: pyfunc() takes 1 positional argument but 4 were given

We can also skip vectorizing on specific arguments, e.g., the 2nd and 4th ones (arguments 1 and 3).

In [10]:
a

array([0, 1, 2, 3, 4])

In [14]:
vpyfunc = np.vectorize(pyfunc, otypes=[float], excluded=[1,3])

print(vpyfunc(a, b, a, d))
print(vpyfunc(b, b, c, d))

[-6. -5.  8.  9. 10.]
8.0


Indeed it fails if the second or the fourth argument is not a single value.

In [15]:
print(vpyfunc(a, a, c, d))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [16]:
print(vpyfunc(a, b, c, a))

ValueError: setting an array element with a sequence.

Finally, notice that
1. calls to NumPy functions are faster than calls to `math` embedded in a vectorized function
1. vectorization wins over comprehensions when the complexity of the operation you are repeating is high

In [23]:
def pyfunc(x):
    return m.log(x*x) - m.sin(x)*m.cos(x)

vpyfunc = np.vectorize(pyfunc)

%timeit np.log(tmp)*np.log(tmp) - np.sin(tmp)*np.cos(tmp)
%timeit vpyfunc(tmp)

857 µs ± 94.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
7.64 ms ± 2.54 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [26]:
%timeit [m.log(x)*m.log(x)**(2-m.log(x)) - m.sin(x)*m.cos(x) for x in tmp]

def pyfunc(x):
    return m.log(x)*m.log(x)**(2-m.log(x)) - m.sin(x)*m.cos(x)

vpyfunc = np.vectorize(pyfunc)


%timeit vpyfunc(tmp)

def pyfunc(x):
    return m.log(x)

vpyfunc = np.vectorize(pyfunc)

# Low complexity: comprehension is faster
%timeit [m.log(x) for x in tmp]
%timeit vpyfunc(tmp)

30.8 ms ± 4.96 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
30.8 ms ± 5.29 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
3.05 ms ± 1.44 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
3.39 ms ± 555 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# 5. Shape of arrays
Every `ndarray` is characterized by its 
- shape
- size
- number of dimensions
- type of data

In [3]:
import numpy as np; import math as m

In [4]:
data = np.array([[-1., 2.3], [2.3, 4.5], [-8.4, 1.9]])
print(data)
print("shape: ", data.shape)
print("size: ", data.size)
print("dimensions: ", data.ndim)
print("data type: ", data.dtype)

[[-1.   2.3]
 [ 2.3  4.5]
 [-8.4  1.9]]
shape:  (3, 2)
size:  6
dimensions:  2
data type:  float64


### Change type of data

In [28]:
data_int = np.array(data, dtype=np.int64)
print(f"original data:\n {data}\n")
print(f"new data:\n {data_int}\n")
print("new data type: ", data_int.dtype)

original data:
 [[-1.   2.3]
 [ 2.3  4.5]
 [-8.4  1.9]]

new data:
 [[-1  2]
 [ 2  4]
 [-8  1]]

new data type:  int64


### Reshaping arrays

In [5]:
data = np.arange(1,37)
print(data)
print(data.ndim)
print(data.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]
1
(36,)


In [6]:
mat1 = data.reshape(3,12)
print(mat1)
print(mat1.ndim)
print(mat1.shape)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32 33 34 35 36]]
2
(3, 12)


In [7]:
mat2 = mat1.reshape(6,6)
print(mat2)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [8]:
mat3 = mat1.reshape(4,3,3)
print(mat3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]


NumPy has its checks on reshaping, so that you do not lose information or add random numbers.

In the following example $10\times 2\times 2\neq 36$, so you hit an error.

In [9]:
mat4 = mat1.reshape(10,2,2)
print(mat4)

ValueError: cannot reshape array of size 36 into shape (10,2,2)

# __Note that the original data array has not been modified__

In [10]:
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

If we want to modify the original array, we need to run `data = data.reshape(6,6)`

### Creating an array with the same shape of an existing array

`ones_like` will give you array elements equal to 1, shaped like its argument

In [11]:
print(mat2)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [12]:
data2 = np.ones_like(mat2)
print(data2)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


`zeros_like` will give you array elements equal to 0, shaped like its argument

In [13]:
np.zeros_like(mat2)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

`full_like` will preserve the shape of the first argument, and give you elements identical to the second argument.

In [14]:
np.full_like(mat2, -4.5, dtype=float)

array([[-4.5, -4.5, -4.5, -4.5, -4.5, -4.5],
       [-4.5, -4.5, -4.5, -4.5, -4.5, -4.5],
       [-4.5, -4.5, -4.5, -4.5, -4.5, -4.5],
       [-4.5, -4.5, -4.5, -4.5, -4.5, -4.5],
       [-4.5, -4.5, -4.5, -4.5, -4.5, -4.5],
       [-4.5, -4.5, -4.5, -4.5, -4.5, -4.5]])

Notice the importance of `dtype`!  The default is `int64` because it is the data type in `mat2`.

In [15]:
np.full_like(mat2, -4.5)

array([[-4, -4, -4, -4, -4, -4],
       [-4, -4, -4, -4, -4, -4],
       [-4, -4, -4, -4, -4, -4],
       [-4, -4, -4, -4, -4, -4],
       [-4, -4, -4, -4, -4, -4],
       [-4, -4, -4, -4, -4, -4]])

Naturally, you can also use the NumPy types.

In [16]:
np.full_like(mat2, fill_value=-4.5, dtype=np.float64)

array([[-4.5, -4.5, -4.5, -4.5, -4.5, -4.5],
       [-4.5, -4.5, -4.5, -4.5, -4.5, -4.5],
       [-4.5, -4.5, -4.5, -4.5, -4.5, -4.5],
       [-4.5, -4.5, -4.5, -4.5, -4.5, -4.5],
       [-4.5, -4.5, -4.5, -4.5, -4.5, -4.5],
       [-4.5, -4.5, -4.5, -4.5, -4.5, -4.5]])

In [17]:
np.full_like(mat2, 'F', dtype=str) # Will fail without the dtype!

array([['F', 'F', 'F', 'F', 'F', 'F'],
       ['F', 'F', 'F', 'F', 'F', 'F'],
       ['F', 'F', 'F', 'F', 'F', 'F'],
       ['F', 'F', 'F', 'F', 'F', 'F'],
       ['F', 'F', 'F', 'F', 'F', 'F'],
       ['F', 'F', 'F', 'F', 'F', 'F']], dtype='<U1')

`empty_like` will give you uninitialized (arbitrary) array elements (not necessarily 0's)

In [18]:
y = np.empty_like(mat2)
print(y)

[[4616752568008179712 4616752568008179712 4616752568008179712
  4616752568008179712 4616752568008179712 4616752568008179712]
 [4616752568008179712 4616752568008179712 4616752568008179712
  4616752568008179712 4616752568008179712 4616752568008179712]
 [4616752568008179712 4616752568008179712 4616752568008179712
  4616752568008179712 4616752568008179712 4616752568008179712]
 [4616752568008179712 4616752568008179712 4616752568008179712
  4616752568008179712 4616752568008179712 4616752568008179712]
 [4616752568008179712 4616752568008179712 4616752568008179712
  4616752568008179712 4616752568008179712 4616752568008179712]
 [4616752568008179712 4616752568008179712 4616752568008179712
  4616752568008179712 4616752568008179712 4616752568008179712]]


# 6. Indexing and slicing

The indexing starts with 0, as usual.

In [19]:
data = np.arange(20).reshape(4,5)
data_l = [[ 0,  1,  2,  3,  4],
          [ 5,  6,  7,  8,  9],
          [10, 11, 12, 13, 14],
          [15, 16, 17, 18, 19]]
print(data)
print(data_l)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14], [15, 16, 17, 18, 19]]


In [20]:
print(data[2:4,2:4])

[[12 13]
 [17 18]]


Note that getting the same with a list requires a more elaborate (and less intuitive) syntax

In [21]:
print(data_l[2:4])

[[10, 11, 12, 13, 14], [15, 16, 17, 18, 19]]


In [22]:
print([el[2:4] for el in data_l[2:4]])

[[12, 13], [17, 18]]


### Extracting columns

In [23]:
print(data)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [24]:
data[:,3] # Fetch the element with index 3 for all values of the 1st index

array([ 3,  8, 13, 18])

In [25]:
data[1:,:] # Fetch all entries for values of the 1st index from 1 onwards

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Slicing for a specific index that is out of bounds will cause an error.

However slicing out of bound indices using `:` will not: NumPy will return as many entries as it can.

In [26]:
data[20]

IndexError: index 20 is out of bounds for axis 0 with size 4

In [27]:
data[20:]

array([], shape=(0, 5), dtype=int64)

In [28]:
data[20:20]

array([], shape=(0, 5), dtype=int64)

In [29]:
data[:2,3:]

array([[3, 4],
       [8, 9]])

In [30]:
data[:2,3:70]

array([[3, 4],
       [8, 9]])

**As with the lists, all operations return a reference to the original array, unless you make a copy**.

In the example below, `y` is a newly defined numpy array, but `x` is not

In [ ]:
x = data[:2,1:3] #so x will modify data, y will not
y = np.array(data[:2,1:3])
print(x)
print(y)

[[1 2]
 [6 7]]
[[1 2]
 [6 7]]


In [ ]:
x[0][1] = -5.55 ##x is a copy, y is not
y[0][1] = 500
print(x)
print(y)
print(data)

[[ 1 -5]
 [ 6  7]]
[[  1 500]
 [  6   7]]
[[ 0  1 -5  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


We have modified not just `x`, but also the original data array!  The same is not true for `y`.

The key difference is that in the `y` case we created a new copy of `data` by calling the constructor `numpy.array`.

# 7. Converting and casting
The following array entries are of integer type.

In [33]:
data = np.arange(9).reshape(3,3)
data.dtype

dtype('int64')

# Sometimes you might want to change its type for floating point calculations

In [34]:
data[1,0] = -np.pi
data

array([[ 0,  1,  2],
       [-3,  4,  5],
       [ 6,  7,  8]])

In [35]:
data_float = data.astype(np.float64)
print(data_float)

[[ 0.  1.  2.]
 [-3.  4.  5.]
 [ 6.  7.  8.]]


In [36]:
data_float[1,0] = -np.pi
print(data_float)

[[ 0.          1.          2.        ]
 [-3.14159265  4.          5.        ]
 [ 6.          7.          8.        ]]


Note that `astype()` returned a copy of the array and our original array `data` has not been modified

In [37]:
print(data)

[[ 0  1  2]
 [-3  4  5]
 [ 6  7  8]]


# 8. Boolean arrays
As with all operations, also logical operations are vectorised.

In [2]:
import numpy as np

In [3]:
data = np.random.normal(0, 1., 9).reshape(3,3) # Same as np.random.normal(0, 1., (3,3))
print(data)

res = data > 0
print(res)

[[-0.96326279  1.23415264  0.98512616]
 [-0.99750745  0.0327357   1.64404081]
 [ 0.38774455  1.86513858 -0.33733676]]
[[False  True  True]
 [False  True  True]
 [ True  True False]]


**Logical arrays can be used to slice and index an array!**

In this case we want the array with just the positive cells.

In [4]:
posdata = data[res]
print(posdata)
print("# positives: ", len(posdata))

[1.23415264 0.98512616 0.0327357  1.64404081 0.38774455 1.86513858]
# positives:  6


Since booleans are converted automatically to 0 and 1, you can easily count them by using the `sum` function

In [5]:
print("Sum of boolean: ", res.sum())

Sum of boolean:  6


Note that the original shape is lost

In [7]:
print(type(posdata))
print("Shape: ", np.shape(posdata))

<class 'numpy.ndarray'>
Shape:  (6,)


**This implies that slicing with a boolean array creates a new array and not a reference to the original array.**

`all()` and `any()` are important methods when dealing with Boolean arrays.
- `all()` checks if all entries are `True`
- `any()` checks that at least on entry is `True`

In [8]:
print(data>0)

print((data>0).all())

print((data>0).any())

[[False  True  True]
 [False  True  True]
 [ True  True False]]
False
True


# 9. I/O of NumPy objects

NumPy provides built-in functions to easily store and read `ndarray`s in binary and text format **without iterating** over each element.
- Use `save()` and `load()` with binary files (`.npy`).
- Use `savetxt()` and `loadtxt()` with textfiles.

### I/O with `ndarray`s: binary and text files

See [Input/Output with numpy](https://numpy.org/doc/stable/reference/routines.io.html) for a general reference.


**Save to file with `save()` and `savetxt()`**

In [9]:
import numpy as np

In [10]:
matrix = np.random.randn(10,5)
print(matrix)

fname = 'npdata1'
np.save(fname+'.npy', matrix)
np.savetxt(fname+'.txt', matrix)

[[ 1.54122493  0.93268726  0.3440095   0.2841221  -0.74687766]
 [ 0.99540436  1.01787172  1.03719339 -0.19119003 -0.35327023]
 [ 1.00014934  2.24853814  1.62505313  0.76570759  0.5926333 ]
 [ 1.49180627 -0.14021374 -0.79768881  0.08615845  0.39933321]
 [-0.24095891  0.40293559  0.25441358  1.81953702 -0.74361573]
 [-1.20308089 -0.7567544   0.42629312  0.42840111  0.50267786]
 [ 0.88669597  0.19645651  1.2208262  -2.53387085  1.18138077]
 [-1.07758767 -0.22401681  0.31511995  0.92703818  0.72416029]
 [ 0.18411223 -0.00883266  0.11513689 -0.10236214  0.18186233]
 [-0.63450257  2.97286037  1.02851004  0.61709227 -1.08314294]]


Naturally, the binary file uses less memory.

In [11]:
!ls -lrth npdata1*

-rw-r--r-- 1 mrtlu mrtlu  528 Jun 15 12:14 npdata1.npy
-rw-r--r-- 1 mrtlu mrtlu 1.3K Jun 15 12:14 npdata1.txt


**Reading is also simple with `load()` and `loadtxt()`**

In [12]:
vals = np.load(fname+'.npy')

assert (vals==matrix).all()

In particular [numpy.loadtxt](https://numpy.org/doc/stable/reference/generated/numpy.loadtxt.html#numpy.loadtxt) is very handy for quick reading of data from text files.

In [13]:
data = np.loadtxt(fname+'.txt')

assert (data==matrix).all()

Slice it to extract columns.

In [14]:
x = data[:,0]
y = data[:,1]
z = data[:,2]
t = data[:,3]
E = data[:,4]

print(z)

[ 0.3440095   1.03719339  1.62505313 -0.79768881  0.25441358  0.42629312
  1.2208262   0.31511995  0.11513689  1.02851004]


We can also think of this txt file as having data stored per event (line) in columns (variables).  E.g., the following structure
```
#x   #y   #z   #t   #energy
...  ...  ...  ...  ...
...  ...  ...  ...  ...
...  ...  ...  ...  ...
```
NB: if you don't use usecols, loadtxt will read the rows!!!!!
Since this is a typical usecase, with NumPy we can also **read the data directly into arrays per column** without reading in all data and then manipulating it.  `loadtxt` has the following options to do this:
- `usecols=(a,b,c)` or `usecols=d` reads only the column(s) specified
- `unpack=True` transposes data to go in columns

In [15]:
x,z = np.loadtxt(fname+'.txt', unpack=True, usecols=(0,2))

assert (z==data[:,2]).all()

Similarly, [nump.savetxt](https://numpy.org/doc/stable/reference/generated/numpy.savetxt.html) is very convenient to **write `ndarrays` by column to textfile** in a formatted fashion.

In [ ]:
fname = 'npdata2.txt'
print(x)
np.savetxt(fname, (x, y, z, t, E), delimiter="\t", fmt="%.3f")

fname = 'npdata3.txt' #here li salvo come colonneee!!
print(x)
np.savetxt(fname, np.array([x, y, z, t, E]).T, delimiter="\t", fmt="%.3f")


[ 1.54122493  0.99540436  1.00014934  1.49180627 -0.24095891 -1.20308089
  0.88669597 -1.07758767  0.18411223 -0.63450257]
[ 1.54122493  0.99540436  1.00014934  1.49180627 -0.24095891 -1.20308089
  0.88669597 -1.07758767  0.18411223 -0.63450257]


# Note that the "columns" get written to lines

In [23]:
!cat npdata2.txt
!cat npdata3.txt

1.541	0.995	1.000	1.492	-0.241	-1.203	0.887	-1.078	0.184	-0.635
0.933	1.018	2.249	-0.140	0.403	-0.757	0.196	-0.224	-0.009	2.973
0.344	1.037	1.625	-0.798	0.254	0.426	1.221	0.315	0.115	1.029
0.284	-0.191	0.766	0.086	1.820	0.428	-2.534	0.927	-0.102	0.617
-0.747	-0.353	0.593	0.399	-0.744	0.503	1.181	0.724	0.182	-1.083
1.541	0.933	0.344	0.284	-0.747
0.995	1.018	1.037	-0.191	-0.353
1.000	2.249	1.625	0.766	0.593
1.492	-0.140	-0.798	0.086	0.399
-0.241	0.403	0.254	1.820	-0.744
-1.203	-0.757	0.426	0.428	0.503
0.887	0.196	1.221	-2.534	1.181
-1.078	-0.224	0.315	0.927	0.724
0.184	-0.009	0.115	-0.102	0.182
-0.635	2.973	1.029	0.617	-1.083


In [19]:
!cat npdata1.txt

1.541224931573206502e+00 9.326872596894486556e-01 3.440095005015816332e-01 2.841221007089126394e-01 -7.468776640810613765e-01
9.954043645302893539e-01 1.017871721340696256e+00 1.037193390808288651e+00 -1.911900306746270872e-01 -3.532702283577988656e-01
1.000149336261119348e+00 2.248538135174750430e+00 1.625053125387937447e+00 7.657075868313792943e-01 5.926332987119969919e-01
1.491806266125933256e+00 -1.402137431309105620e-01 -7.976888127666938999e-01 8.615845372193672858e-02 3.993332095085316280e-01
-2.409589135445507624e-01 4.029355883001133898e-01 2.544135846470351181e-01 1.819537020549303552e+00 -7.436157265820309004e-01
-1.203080893050319178e+00 -7.567543970764004646e-01 4.262931240254563825e-01 4.284011140785567995e-01 5.026778590284001202e-01
8.866959684484345683e-01 1.964565102083919157e-01 1.220826198144993491e+00 -2.533870852493548931e+00 1.181380774433130387e+00
-1.077587673999200080e+00 -2.240168058927903827e-01 3.151199528201553135e-01 9.270381833498945179e-01 7.24160285098

Cleanup

In [20]:
!rm npdata*

The [Python Data Analysis Library (pandas)](http://pandas.pydata.org) provides even more efficient tools and data formats to handle data for analysis and their storage to file.